#!/usr/bin/groovy
pipeline {
	agent any
	options { timestamps() }
	stages {

		stage('Build') {
			steps {
				pwd tmp: true			
				echo 'Building..'
				sh "pwd"
			}
		}

		stage('Test') {
			steps {
				echo 'Testing..'
			}
		}

		stage('Deploy') {
			steps {
				echo 'Deploying....'
			}
		}

	}
}
